### ISSUE TITLE
Actual data

### ISSUE THREAD

**Issue by EMattfolk** [lithekod/user-database#1]
Find a way to import the current database into the new one.

**Comment by Emiluren** [comment]
Lol, varför är jag subscribad till den här?

**Comment by EMattfolk** [comment]
Inte helt säker. Kanske för att du är med i lithekod gruppen? Borde du inte ha sett detta?

**Comment by Emiluren** [comment]
Antar det är så. Trodde inte jag skulle bli notifierad om en issue i ett repo jag inte varit med att skapa. Men det har väl nåt med organistationen att göra.
